spring:
  thymeleaf:
    cache: false
  mvc:
    static-path-pattern: /**
  web:
    resources:
      static-locations: classpath:/static/
      cache:
        period: 0
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/spring_auth_server?createDatabaseIfNotExist=true&useUnicode=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true
    username: ${MYSQL_USERNAME:root} # update username
    password: ${MYSQL_PASSWORD:password} # update password
  jpa:
    hibernate:
      ddl-auto: update
#  flyway:
#    baseline-on-migrate: true
#    baseline-description: <<Flyway Baseline>>
#    enabled: true
#    locations: classpath:db/migration
#    validate-on-migrate: true
#    fail-on-missing-locations: true

logging:
  level:
    root: INFO
    org.springframework.web: INFO
    org.springframework.security: TRACE
    org.springframework.security.oauth2: TRACE
